name: WGPFix
main: me.asofold.bpl.fix.wgp.WGPFix
#version: ${project.version}
version: 2.2.1
softdepend:
- WorldGuard
- WorldEdit
commands:
    wgpfix:
        description: For reloading settings
        usage: 'wgpfix <cmd> : reload, panic, unpanic, monitor, unmonitor'
