name: WGPFix
main: asofold.fix.wgp.WGPFix
version: 1.4.1
softdepend:
- WorldGuard
- WorldEdit
commands:
    wgpfix:
        description: For reloading settings
        usage: 'wgpfix <cmd> : reload, panic, unpanic, monitor, unmonitor'