name: WGPFix
main: me.asofold.bpl.fix.wgp.WGPFix
#version: 2.3.1
api-version: 1.13
version: 2.3.1
softdepend:
- WorldGuard
- WorldEdit
commands:
    wgpfix:
        description: For reloading settings
        usage: 'wgpfix <cmd> : reload, panic, unpanic, monitor, unmonitor'
