name: WGPFix
main: me.asofold.bpl.fix.wgp.WGPFix
version: ${project.version}-b${BUILD_NUMBER}
softdepend:
- WorldGuard
- WorldEdit
commands:
    wgpfix:
        description: For reloading settings
        usage: 'wgpfix <cmd> : reload, panic, unpanic, monitor, unmonitor'