name: WGPFix
main: me.asofold.bukkit.fix.wgp.WGPFix
version: 2.0.0
softdepend:
- WorldGuard
- WorldEdit
commands:
    wgpfix:
        description: For reloading settings
        usage: 'wgpfix <cmd> : reload, panic, unpanic, monitor, unmonitor'